### ISSUE TITLE
An empty placeholder instead of episodes in the playlist goes on forever

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#237] opened 2023-06-03 17:22 UTC
This happens sometimes. I don't know how to reproduce it.
![Screenshot_2023-06-02-09-29-44-234_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/a983d242-384f-4355-b1e9-40c2796a6447)

**Comment by gemiren** [comment] 2023-06-03 23:56
This is the new shimmer effect added in the latest beta. This empty placeholder is displayed if the episode hasn't been loaded for display yet.

A related change in the latest beta is that the app now will scroll to an episode which isn't loaded into the list yet. The previous behavior is that the app will scroll to the episode if it's already been loaded into the list, otherwise, just returns to the top of the list.

If you have a large number of episodes in a list, when displaying the list, the app doesn't wait for all episodes to be loaded. Instead, the app only loads the first 60 episodes so that the list can be displayed faster. The rest of the list will be loaded when you scroll down the list.

Now, if you scroll down the list quickly, the app may not be able to load the corresponding episodes quick enough to display them. If this happens, this new shimmer effect placeholder is displayed till the episode gets loaded.

**Comment by vlzuykov** [comment] 2023-06-04 08:26
From what I understand, this effect should last for a few miliseconds (or just over a second if process or RAM is busy). But when this screenshot was taken this shimmer went on for almost forever and there were only 36 episodes in the playlist.

**Comment by vlzuykov** [comment] 2023-06-04 08:34
https://youtu.be/d6iFToXmCOI

**Comment by vlzuykov** [comment] 2023-07-13 19:27
This seems to have been fixed in the latest beta.

**Comment by gemiren** [comment] 2024-01-27 22:59
> Episodes not loading is a really frequent error and screws me from time to time. I usually have a large list of episodes (currently around 150) I've not listened to and do 'cluster' them as some of those are 1-2minutes long and I like to binge them if I'm in the mood.
> 
> So I usually drag a new episode manually to the cluster.
> 
> Every few days this loading error happens. If I'm dragging too fast to stop before the placeholders it can screw up the order of the episodes.
> Usually it moves several episodes to a new position after restarting the app.
> It can also happen that I can scroll (seemingly?) endlessly in the list if many episodes didn't load.
> 
> Please fix that soon, as it's really starting to bother me that I have to work around this several times a week.
> Thanks!
> 
> If I can do something to help: don't hesitate to ask!

This bug should be fixed in today's beta update.  Please give it a try and let me know if the issue is still there. Thanks.

**Comment by vlzuykov** [comment] 2024-01-28 08:49
It was fixed

**Comment by gemiren** [comment] 2024-01-28 13:22
> It was fixed

Awesome. Thanks very much for confirming the fix.

**Closed** 2024-01-28 13:22 UTC

**Comment by Thalonius** [comment] 2024-01-30 06:43
That problem seems fixed, but there are still funky things happening. I'll make a new entry.

Thanks for the fast change!
