### ISSUE TITLE
More episodes - No more episodes to play from playlist

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#343] opened 2023-10-12 16:27 UTC
There is a playlist that contains several episodes.
After playing the first episode, the playback does not continue, but the next (error) message is displayed:

No more episodes to play from playlist [ ]

In Hungary: Nincs több epizód a lejátszólistán [ ]

Why?

In addition, the name of the playlist (parameter %1$s) is not displayed in the message:

<string name="no_more_episodes_to_play_from_playlist_s_">No more episodes to play from playlist [%1$s].</string>

![Screenshot_20231012-170355_Podcast Republic](https://github.com/Podcast-Republic/PRApp/assets/3171626/f4ce65fe-0fe7-4f45-bddb-ff531f24a706)

![Screenshot_20231012-174327_Podcast Republic](https://github.com/Podcast-Republic/PRApp/assets/3171626/3769ac4f-9a88-4cc4-8e63-67604541cfee)

**Comment by gemiren** [comment] 2023-10-13 12:33
Can you go to app Settings > Playlists to double check whether you have 'Update Up next automatically' option enabled? Thanks.

**Comment by gemiren** [comment] 2023-10-14 14:53
Can you send the app log? Please send the app log after reproducing the issue. Thanks.

**Comment by fredsleeve** [comment] 2024-07-24 22:46
I'm facing the same "issue". But I think there's misunderstanding with the Prev/Next button and playlist. Please correct me, if I am wrong:
Next/Prev only works when there's something in "Up Next". If I am in a playlist and there's nothing in "Up Next" this message occur. When enabling 'Update Up next automatically', the buttons are starting to work when start playing an episode from an playlist as te "Up next" will be filled.
If this is right, you should consider to disable the buttons or show a proper error message. In this case the message "No more episodes to play from playlist [%1$s]." should point to "Up next".

**Comment by fredsleeve** [comment] 2024-07-24 23:01
Addtional finding: When you disable 'Update Up next automatically' after a few episodes are in "Up next", then adding a new episode to your custom playlist with disabed, the newly added episode will be ignored by the Prev/Next button.

**Comment by gemiren** [comment] 2024-07-24 23:21
Nice findings. Will look into that. Thanks!

**Comment by fredsleeve** [comment] 2024-08-04 19:37
Were you able to reproduce this? Problem still exists in latest beta 24.8.4b. Tell me if you need more input.

**Comment by gemiren** [comment] 2024-08-05 03:23
> In this case the message "No more episodes to play from playlist [%1$s]." should point to "Up next".

Agreed, the message should point to 'Up next' instead of the playlist. Will fix that asap. Thanks.

**Comment by fredsleeve** [comment] 2024-08-25 17:02
Seems to be fixed in 24.8.22b as now a proper message occurs. I think this can be closed.

**Closed** 2024-08-29 22:15 UTC
