### ISSUE TITLE
Deleting a playlist changes the sorting criteria of another playlist

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#231] opened 2023-05-27 17:07 UTC
The first playlist is sorted manually. When I delete the second playlist, sorting criteria of the first one changes to sort by publication date.

**Comment by gemiren** [comment] 2023-05-29 02:34
Are you able to reproduce this bug? I tried a few times but couldn't reproduce it. Any steps I can follow to reproduce this bug? Thanks.

**Comment by vlzuykov** [comment] 2023-05-29 04:50
I can reproduce this bug every time I try.  This bug only affects the first playlist, no matter how many there are.
https://youtu.be/DJAVXiYxWkg

**Comment by vlzuykov** [comment] 2023-05-29 05:01
Exception: the bug doesn't reproduces when I don't tap at this new playlist right before deleting it.
https://youtu.be/K4BnMRwU8qQ

**Comment by vlzuykov** [comment] 2023-05-29 05:09
Addition: After deleting a playlist, the sorting criterion of the first playlist changes to the one that was in the deleted playlist. So if the deleted playlist was manually sorted, then the sorting criteria of the first one does not change.

**Comment by gemiren** [comment] 2023-05-30 13:02
Thanks very much for the video. However, I'm still not able to reproduce this bug. Can you go to app Settings > Backup & restore to create a backup of the app data and then send the backup file to tech@podcastrepublic.net? Thanks.

**Comment by gemiren** [comment] 2023-05-30 14:03
Thanks very much for sending the backup. That's really helpful. I was able to reproduce the bug and got it fixed. The fix will be in the next update. Thanks.

**Closed** 2023-06-01 18:18 UTC
