### ISSUE TITLE
[Problem] Marking RSS feeds as read

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#59] opened 2021-11-14 09:41 UTC
Marking RSS feeds as read isn't good, after "**Mark all feeds as read**", a "**Refresh**" will mark what you've already read as new.

**Comment by gemiren** [comment] 2021-11-15 02:00
The app uses guid (global unique id) to identify whether two articles are same or not. I suspect the article's guid may get changed so that old articles are retrieved as "new" again. Please let me know the feed URL. I can double check that. Thanks.

**Comment by oldman63** [comment] 2021-11-16 06:40
For example: [https://lazarbibi.blog.hu/rss](https://lazarbibi.blog.hu/rss)

The checking process:

1. Add RSS-Feed
2. Refresh in RSS-Feed list
2. Mark all as read
3. Refresh
4. All news already read will appear as new

Tip: If you open the feed and do the above again, it will work correctly!

**Comment by gemiren** [comment] 2021-11-18 00:00
I followed the steps but couldn't reproduce the bug. Here is my screen recording https://www.dropbox.com/s/tcyv4yppzjgmv7q/mark_as_read_bug.webm?dl=0. Maybe I missed something?

**Comment by oldman63** [comment] 2021-11-18 07:14
> Here is my screen recording

Thank you for your control.

Here is my "extended" screen recording: [Google Photos](https://photos.app.goo.gl/y5GBG56mVKSLr12k8)

It seems problematic to me.

**Comment by gemiren** [comment] 2021-11-19 03:25
Thanks for the video. I was able to reproduce the bug. Will get it fixed asap.

**Comment by gemiren** [comment] 2021-11-20 00:13
Fixed in today's beta update. Thanks.

**Comment by oldman63** [comment] 2021-11-22 12:15
Nearly perfect.

This feed is still problematic: [Megatools](https://megatools.megous.com/rss.xml)

**Comment by gemiren** [comment] 2021-11-23 00:33
Yeah, I can reproduce the bug with Megatools feed. Will get it fixed in next update. Thanks.

**Comment by gemiren** [comment] 2021-11-24 00:08
Fixed in today's beta update.

**Comment by oldman63** [comment] 2021-11-24 07:11
21.11.23b
I see it works well!

**Comment by gemiren** [comment] 2021-11-24 08:17
Great. Thanks for confirming the fix.

**Closed by gemiren** 2021-11-24 08:17 UTC
